---
- name: Install Required Packages
  apt:
    name:
      - apache2
      - python3
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Ensure Apache is Running
  service:
    name: apache2
    state: started
    enabled: yes

- name: Allow Required Ports in Firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 8080
    - 8090

- name: Ensure target directory exists
  become: yes
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy Flask dependencies file
  become: yes
  ansible.builtin.copy:
    src: files/web-app/requirements.txt
    dest: /var/www/html/requirements.txt
    owner: www-data
    group: www-data
    mode: '0644'
    force: yes

- name: Verify the file was copied
  command: ls -l /var/www/html/requirements.txt
  register: file_status
  changed_when: false

- name: Debug file copy result
  debug:
    msg: "{{ file_status.stdout_lines }}"

- name: Install Flask dependencies
  pip:
    requirements: /var/www/html/requirements.txt
    executable: pip3
  register: pip_install
  ignore_errors: yes  # Allow debugging even if it fails

- name: Debug pip installation
  debug:
    msg: "{{ pip_install.stderr }}"
  when: pip_install.failed

- name: Copy Apache Virtual Host Configuration
  template:
    src: templates/apache.conf.j2
    dest: "/etc/apache2/sites-available/{{ inventory_hostname }}.conf"

- name: Enable the New Site Configuration
  command: "a2ensite {{ inventory_hostname }}.conf"

- name: Restart Apache to Apply Changes
  service:
    name: apache2
    state: restarted
